### PR TITLE
Adds Centos Tutorial EN

### PR DESCRIPTION
**Pull request by Morketh**
Well here it is: a Centos 7 install guide. @AntzMangos have a look

### CODE REVIEW

**Comment by billy1arm** [comment]
@Morketh many thanks for this

**Comment by Morketh** [comment]
@billy1arm Thank you for the opportunity to be apart of this project you guys have done some awesome work here.

**Comment by billy1arm** [comment]
this should now be fixed, the markdown used on the website appears to not be 100% compatible with githubs'.

especially the '''bash/sql code delimiter blocks.

**Comment by Morketh** [comment]
i believe there is still an error with a Large number of bold text O_O i will look at the original and see if that was supposed to be like that.

**Comment by Faded** [comment]
I wouldn't worry about the linux sections. I still plan to re write the centos and others

**Comment by Morketh** [comment]
if you need help with the Centos Page let me know I wrote the original one.

**Comment by billy1arm** [comment]
@Faded - Do you think you will be able to produce anything in the next week or so ?

**Comment by nom-soft** [comment]
@billy1arm, unfortunately no. I've been pretty busy with our parent co. Nomsoft with game releases

**Comment by Morketh** [comment]
I could get something put together in the next week. i have all the original work would just need to know the difference between Mangos Markdown and the Github variant. after that it would be a simple reformat for the original paper

**Pull request merged**
